<?xml version="1.0" encoding="utf-8"?><testsuite errors="1" failures="1" name="pytest" skips="0" tests="2" time="28.170"><testcase classname="tests.test_CodeId" file="tests/test_CodeId.py" line="11" name="test_CodeId[5001-5000-UPC-A0]" time="8.49223566055"><failure message="NameError: global name &apos;level&apos; is not defined">test_CodeId.py:17: in test_CodeId
    assert output == device.scanner.scan(symbology_num, subtest, barcode[0], size, use)
../lib/scanner.py:19: in scan
    msg = &apos;lipc-set-prop com.lab126.powerd flIntensity {}\r&apos;.format(level)
E   NameError: global name &apos;level&apos; is not defined</failure></testcase><testcase classname="tests.test_CodeId" file="tests/test_CodeId.py" line="11" name="test_CodeId[5001-5000-UPC-A1]" time="2.0948472023"><error message="test setup failure">../conftest.py:183: in logfolder
    os.makedirs(logfolder)
../../venv27/lib/python2.7/os.py:157: in makedirs
    mkdir(name, mode)
E   OSError: [Errno 17] File exists: &apos;logs/21062022_104424.478486/21342522506311&apos;</error></testcase></testsuite>